project:
  type: website
  output-dir: docs

website:
  title: "Jack Hagenbuch"
  navbar:
    left:
      - href: index.qmd
        text: About
      - Photography.qmd
      - Research.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

