project:
  type: website
  output-dir: docs

website:
  title: "Jack Hagenbuch"
  navbar:
    left:
      - href: index.qmd
        text: About
      - Photography.qmd
      - Research.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/jack-hagenbuch/

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

